<<<<<<< HEAD
name: build

=======
name: Node CI





# Trigger the workflow on push or pull request
>>>>>>> 9ab0544beb944615134119f25870181bcad658da
on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
<<<<<<< HEAD

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
=======
        
        name: Use Node.js ${{ matrix.node-version }}
        # Configures the node version used on GitHub-hosted runners
    uses: actions/setup-node@v1
        # The Node.js version to configure
>>>>>>> 9ab0544beb944615134119f25870181bcad658da
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: make install

        env:
          CI: true

      - name: Run ESLint
        run: make lint
